"""Adding Column Thumbnail for Video Table

Revision ID: e41e65c51789
Revises: 2e749cdc30c1
Create Date: 2025-06-04 11:01:50.507251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41e65c51789'
down_revision: Union[str, None] = '2e749cdc30c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumbnail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumbnail')
    # ### end Alembic commands ###
